Revised the README to target the certification audience.
cncf/k8s-conformance pull request #10
Opened 2017-10-09 21:54 UTC by WilliamDenniss

Moved WG materials to README-WG.md

2017-10-09 22:00 UTC, dankohn commented on README-WG.md
> +Info regarding the CNCF K8s Conformance Working Group.
Please kill this line.

2017-10-09 22:01 UTC, dankohn commented on README-WG.md
> +The Kubernetes Software Conformance Working Group operates under the aegis of CNCF. We are collaborating with the Kubernetes [Architecture](https://github.com/kubernetes/community/blob/master/sig-arc
Could you please update this description to describe exactly how we're collaborating with them, as per the blog post.

2017-10-09 22:14 UTC, dankohn commented
LGTM after you address my 2 comments. Thanks.

2017-10-09 22:47 UTC, WilliamDenniss commented
Updated, PTAL.

2017-10-09 23:19 UTC, dankohn commented
+1

2017-10-09 23:24 UTC, merged

2023-01-07 00:01 UTC, Kato129 reviewed
Delete this

2024-08-11 20:27 UTC, timscharfenort8 requested changes
good work