Send conformance test for minikube
cncf/k8s-conformance pull request #1220
Opened 2020-11-28 07:17 UTC by azhao155

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

2020-11-30 18:18 UTC, medyagh requested changes

2020-11-30 18:18 UTC, medyagh commented on v1.19/minikube/README.md
> +Run minikube with 2 nodes and containerd runtime.
add a note here that docker run-time is not confmrant and "containerd" runtime is needed.

2020-12-04 23:12 UTC, taylorwaggoner commented
@azhao155 @medyagh is this ready for review or are more changes needed per the suggestions?

2020-12-07 05:37 UTC, azhao155 commented
@taylorwaggoner It's ready for review now. Thanks

2020-12-11 23:46 UTC, taylorwaggoner commented
You are now Certified Kubernetes

2020-12-11 23:46 UTC, merged