Conformance results for v1.22/digitalocean
cncf/k8s-conformance pull request #1821
Opened 2022-03-04 18:13 UTC by elijahomolo

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [x ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [ x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

2022-03-04 18:34 UTC, waynr requested changes

2022-03-04 18:34 UTC, waynr commented on v1.22/digitalocean/PRODUCT.yaml
> +version: v1.21.7-do.0
This should be `1.22.7-do.0`.

2022-03-04 18:34 UTC, waynr commented on v1.22/digitalocean/README.md
> +$ doctl kubernetes cluster create --version 1.21.2-do.0 do-sonobuoy-1212 --node-pool "name=conformance;size=s-4vcpu-8gb;count=3" --wait
The version shown here is wrong.

2022-03-04 18:34 UTC, waynr commented on v1.22/digitalocean/PRODUCT.yaml
> +version: v1.21.7-do.0
(i don't know for sure, but the wrong version listed here could lead CI checks on this PR to fail)

2022-03-04 21:50 UTC, waynr commented
/retest

2022-03-07 19:39 UTC, taylorwaggoner commented
You are now Certified Kubernetes

2022-03-07 19:39 UTC, merged